apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostra-dataload-host
  labels:
    app: nostra-dataload-host
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nostra-dataload-host
  template:
    metadata:
      labels:
        app: nostra-dataload-host
    spec:
      containers:
      - name: nostra-dataload-host
        image: ${REGISTRY}/nostra-dataload-host:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultSqlConnection
          valueFrom:
            secretKeyRef:
              name: nostra-dataload-secrets
              key: default-sql-connection
        - name: ConnectionStrings__TaskQueueConnection
          valueFrom:
            secretKeyRef:
              name: nostra-dataload-secrets
              key: task-queue-connection
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nostra-dataload-host
spec:
  selector:
    app: nostra-dataload-host
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: nostra-dataload-secrets
type: Opaque
data:
  default-sql-connection: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1Ob3N0cmFfRGF0YWxvYWQ7VXNlciBJZD1zYTtQYXNzd29yZD1QYXNzd29yZDEyMyE7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlOw==
  task-queue-connection: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1Ob3N0cmFfRGF0YWxvYWRfVGFza3M7VXNlciBJZD1zYTtQYXNzd29yZD1QYXNzd29yZDEyMyE7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlOw==